DROP TABLE IF EXISTS fleets CASCADE;
DROP TABLE IF EXISTS ships CASCADE;
DROP TABLE IF EXISTS assignments CASCADE;
DROP TABLE IF EXISTS sailors CASCADE;
DROP TABLE IF EXISTS ranks CASCADE;
DROP TABLE IF EXISTS duties CASCADE;

CREATE TABLE fleets (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE ships (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  date_build DATE NOT NULL,
  fleet_id INTEGER NOT NULL REFERENCES fleets(id) ON DELETE CASCADE
);

CREATE TABLE sailors (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(100) NOT NULL,
  date_of_birth DATE NOT NULL
);

CREATE TABLE ranks (
  id SERIAL PRIMARY KEY NOT NULL,
  ship_id INTEGER NOT NULL REFERENCES ships(id) ON DELETE CASCADE,
  sailor_id INTEGER NOT NULL REFERENCES sailors(id) ON DELETE CASCADE,
  rank_description VARCHAR(100) NOT NULL
);

CREATE TABLE duties (
  id SERIAL PRIMARY KEY NOT NULL,
  rank_id INTEGER NOT NULL REFERENCES ranks(id) ON DELETE CASCADE,
  duty_description VARCHAR(100) NOT NULL
);

CREATE TABLE assignments (
  id SERIAL PRIMARY KEY NOT NULL,
  ship_id INTEGER NOT NULL REFERENCES ships(id) ON DELETE CASCADE,
  sailor_id INTEGER NOT NULL REFERENCES sailors(id) ON DELETE CASCADE,
  duty_id INTEGER NOT NULL REFERENCES duties(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL
);

INSERT INTO "fleets" (name) VALUES('Black Oyster');
INSERT INTO "ships" (name, date_build, fleet_ID) VALUES('Alaunia II', 'January 15th, 1993', 1);
INSERT INTO "ships" (name, date_build, fleet_ID) VALUES('Duke William', 'December 19th, 1976', 2);


SELECT * FROM fleets;
SELECT * FROM ships;
SELECT * FROM sailors;
SELECT * FROM ranks;
SELECT * FROM duties;
SELECT * FROM assignments;